### PR TITLE
Update yardstick to 0.0.2

### PR DESCRIPTION
**Pull request by philip-khor**
Requirement to add [tidymodels](https://cran.r-project.org/web/packages/tidymodels/index.html) to conda-forge 

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by philip-khor** [comment]
@conda-forge-admin, please rerender

**Comment by philip-khor** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
Seems like now the recipe is fine, but r-generics is not available with gcc7 label https://anaconda.org/conda-forge/r-generics/files

**Comment by dbast** [comment]
Related to https://github.com/conda-forge/conda-forge.github.io/issues/674

**Comment by bgruening** [comment]
relabled the packages and restarted the builds

**Comment by bgruening** [comment]
Mh, it seems OSX builds are missing :( https://anaconda.org/conda-forge/r-yardstick/files
And the non GCC7 builds are missing win and OSX.

**Pull request merged**
